LR:
  d: 38
  u: 87
  s: 90
  w: 33
CV:
  d: 0.1
  u: 0.9
  s: 0.2
  w: 1.2
m:
  d: 1.5
  u: 1.45
  s: 1.56
  w: 1.33

Gf_range:
  d: [0.000010, 0.000050]
  u: [0.000010, 0.000100]
  s: [0.000200, 0.000600]
  w: [0.00005, 0.000010]

delta_range:
  d: [0.20, 0.35]
  u: [0.05, 0.15]
  s: [0.01, 0.10]
  w: [0.001, 0.01]
NSamples: 100
N1: 10
epsilon: 0.2
workers: 4
log_level: debug
method: gradient
