LR:
  d: 49
  u: 46
  s: 65
  w: 33
CV:
  d: 0.07
  u: 0.08
  s: 0.085
  w: 0.12

Gf_range:
  d: [1e-5, 1e-4]
  u: [1e-5, 1e-4]
  s: [2e-4, 1e-3]
  w: [1e-9, 1e-5]

m_range:
  d: [1.40, 1.45]
  u: [1.55, 1.53]
  s: [1.51, 1.54]
  w: [1.33, 1.35]

delta_range:
  d: [0.20, 0.35]
  u: [0.05, 0.15]
  s: [0.01, 0.10]
  w: [0.001, 0.01]
NSamples: 100
N1: 10
epsilon: 0.15
workers: 7
log_level: debug
method: nelder-mead
log_file: log.txt
decimals_default: 2
decimals_gf: 6
